<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ind0003854" name="com.madhub.demo.codingTest.TC5_PutServiceTest" tests="1" failures="1" timestamp="4 May 2019 20:45:02 GMT" time="1.037" errors="0">
  <testcase name="PUTServiceTest" time="1.037" classname="com.madhub.demo.codingTest.TC5_PutServiceTest">
    <failure type="junit.framework.AssertionFailedError" message="[Validting Newly Created/Updated Resource]: &quot;title&quot; value is not as expected.  Value requested =abc, but received=sunt aut facere repellat provident occaecati excepturi optio reprehenderit">
      <![CDATA[junit.framework.AssertionFailedError: [Validting Newly Created/Updated Resource]: "title" value is not as expected.  Value requested =abc, but received=sunt aut facere repellat provident occaecati excepturi optio reprehenderit
	at junit.framework.Assert.fail(Assert.java:50)
	at core.ResponseValidators.compareResponseData(ResponseValidators.java:67)
	at com.madhub.demo.codingTest.TC5_PutServiceTest.PUTServiceTest(TC5_PutServiceTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- PUTServiceTest -->
</testsuite> <!-- com.madhub.demo.codingTest.TC5_PutServiceTest -->
